### PR TITLE
feature/BRIDGE-941

### PR DESCRIPTION
**Pull request by dephillipsmichael**
THIS PR IS DEPENDENT ON https://github.com/Sage-Bionetworks/AppCore/pull/97 and https://github.com/Sage-Bionetworks/ResearchKit/pull/13 THESE MUST BE MERGED FIRST.

Enabled forgot passcode feature in ResearchKit.

### CODE REVIEW

**Comment by syoung-smallwisdom** [comment]
Needs to be updated to match new delegate methods. (sorry)

**Comment by dephillipsmichael** [comment]
Updated.

**Comment by syoung-smallwisdom** [comment]
Closing. The APHOnboardingManager only adds a passcode view controller with itself as the delegate for the case where it is _adding_ a passcode and not where it is authenticating an existing passcode.

**Comment by dephillipsmichael** [comment]
Ah, good point.  I was confused why there were two passcode delegates in the mPower project.

**Comment by syoung-smallwisdom** [comment]
Yeah, it's confusing. (sorry) Reverse-compatibility. There was too much work and I didn't have time to move entirely away from the view controllers in AppCore which are _not_ ORKStepViewControllers, and some of which do not render well when inheriting from that class with an ORKTaskViewController as the parent. My compromise was to have the APCAppDelegate implement _both_ the APC passcode delegate and the ORK passcode delegate for the _authentication_ but to keep the creation/edit implementation in the onboarding manager.

**Pull request closed without merging**
