### PR TITLE
Onboarding and consent

### PR DESCRIPTION
**Pull request by syoung-smallwisdom**
Changed onboarding to use inline consent flow using ORKTask and ORKStepViewControllers. Moved the html for consent into the public repo.

### CODE REVIEW

**Comment by Erin-Mounts** [comment]
looks good

**Comment by evliu** [comment]
I tried building this against all new changes and get an issue with ResearchKit redefinitions (which I'm guessing one is clobbering the other) but it works on the commit right before the merge; any advice?

**Comment by Erin-Mounts** [comment]
try now? I'd been having the same trouble with the previous commit and had a solution which I hadn't pushed yet--but have now...

**Comment by Erin-Mounts** [comment]
(you'll need to pull the latest BridgeAppSDK, I just updated it and updated the private app repo to point to the latest commit of that submodule)

**Comment by evliu** [comment]
Thanks. I found every few times I try building with AppCode, it would build for some reason, lol. Maybe I should also try building with xctool for better logging. Anyways, just tried and looks like it works now. Thanks!

**Pull request merged**
